#pragma once

// display related added clips
// play stop clips via button, list clicks, or hotkeys
// register and unregister hotkeys per-clips
// persistent clip list/hotkeys and the global audio hotkeys

#include <QWidget>
#include <QListWidgetItem>
#include <QMap>
#include <QString>
#include <QMenu>
#include <QAction>

// wrapper
#include <obs.hpp>
//  ui builder
#include "ui_Soundboard.h"

// reflect
#include "hotkeys/HotkeyManager.hpp"
#include "source/SourceManager.hpp"
#include "persistence/SoundboardStore.hpp"  


// inherit the QWidget (for it to show in OBS and interact with it, you get the point)
class Soundboard : public QWidget {
    Q_OBJECT

public:
    //  construction and deconstruction of soundboard
    explicit Soundboard(QWidget*parent = nullptr);
    ~Soundboard();

    //  persistence / data / source callbacks

    QListWidget *getList() { return ui.list; }
    SourceManager &getSourceManager() { return source; }
    
    // ── Last played item tracking ──────────────────────────────
    QListWidgetItem *getLastPlayedItem() const { return lastPlayedItem; }
    void setLastPlayedItem(QListWidgetItem *item) { lastPlayedItem = item; }
    QListWidgetItem *findItemByPath(const QString &path) const;
 
    // ── Persistence (called by plugin-main save/load hook) ──
    void saveData(obs_data_t *data); // delegate → SoundboardStore::save()
    void loadData(obs_data_t *data); // delegate → SoundboardStore::load()
 
    // ── OBS source lifecycle (called by plugin-main events) ─
    void ensureSource(); // delegate → SourceManager::ensureSource()
    void clearSource();  // delegate → SourceManager::clearSource()

private slots:
    // ── UI signal handlers ───────────────────────────────────
    void onItemClicked(QListWidgetItem *item);      // click → play
    void onAddClicked();                            // Add button
    void onPlayClicked();                           // Play button
    void onStopClicked();                           // Stop button
    void onRemoveClicked();                         // Remove button
    void onContextMenuRequested(const QPoint &pos); // right-click list
    void onEditItem(QListWidgetItem *item);         // Edit from context menu
 
private:
    // ── UI ───────────────────────────────────────────────────
    Ui::Soundboard ui; // generated by Qt Designer
 
    // ── Managers (value members — no raw owning pointers) ───
    HotkeyManager  hotkeys; // per-clip + global hotkey registration
    SourceManager  source;  // ffmpeg_source creation and playback
    SoundboardStore store;  // clip list serialization / deserialization
    
    // ── Track last played item ──────────────────────────────
    QListWidgetItem *lastPlayedItem = nullptr;
};
