#pragma once

// ============================================================
// Soundboard.hpp
// Main dock widget for the OBS Soundboard plugin.
//
// Responsibilities:
//   - Display a list of named audio clips
//   - Play/stop clips via buttons, list clicks, or hotkeys
//   - Register/unregister per-clip OBS frontend hotkeys
//   - Persist clip list and hotkey bindings through OBS save/load
// ============================================================

#include <QWidget>
#include <QListWidgetItem>
#include <QMap>
#include <QString>
#include <QMenu>
#include <QAction>

#include <obs.hpp> // OBSSource RAII wrapper
#include "ui_Soundboard.h"

class Soundboard : public QWidget {
	Q_OBJECT

public:
	// ── Construction / destruction ──────────────────────────
	explicit Soundboard(QWidget *parent = nullptr);
	~Soundboard();

	// ── Accessors ───────────────────────────────────────────
	// Expose the list widget so external code can inspect it if needed.
	QListWidget *getList() { return ui.list; }

	// ── Persistence (called by plugin-main save/load hook) ──
	void saveData(obs_data_t *data); // Serialize clips + hotkey bindings → obs_data
	void loadData(obs_data_t *data); // Deserialize and rebuild clips + hotkey bindings

	// ── OBS source lifecycle ─────────────────────────────────
	// ensureSource: create (or reuse) the hidden ffmpeg_source used for playback.
	void ensureSource();
	// clearSource: detach from output slot 63 and release the source reference.
	void clearSource();

	// ── Playback ─────────────────────────────────────────────
	// Play the audio file at the given absolute path.
	// Called both from UI interactions and from hotkey callbacks.
	void playFile(const QString &path);

private slots:
	// ── UI signal handlers ───────────────────────────────────
	void onItemClicked(QListWidgetItem *item);      // Single-click a clip → play it
	void onAddClicked();                            // "Add" button → open AddSoundDialog
	void onPlayClicked();                           // "Play" button → play selected clip
	void onStopClicked();                           // "Stop" button → stop playback
	void onRemoveClicked();                         // "Remove" button → delete selected clip
	void onContextMenuRequested(const QPoint &pos); // Right-click on list → show context menu
	void onEditItem(QListWidgetItem *item);         // "Edit" from context menu → re-open dialog

private:
	// ── Hotkey helpers ───────────────────────────────────────
	// Register a new OBS frontend hotkey for the given list item.
	void registerHotkey(QListWidgetItem *item);
	// Unregister the hotkey associated with the given list item.
	void unregisterHotkey(QListWidgetItem *item);
	// Unregister hotkeys for every item currently in the list.
	void unregisterAllHotkeys();

private:
	// ── UI (generated by Qt Designer) ───────────────────────
	Ui::Soundboard ui;

	// ── Playback state ───────────────────────────────────────
	OBSSource mediaSource = nullptr; // RAII wrapper around the hidden ffmpeg_source
	QString currentFile;             // Path of the file most recently sent to the source

	// ── Hotkey bookkeeping ───────────────────────────────────
	// Item data roles:
	//   Qt::UserRole     → absolute file path (QString)
	//   Qt::UserRole + 1 → stable unique ID   (QString UUID)
	//
	// Both maps are keyed by that UUID so lookups survive item renames/re-paths.
	QMap<QString, obs_hotkey_id> hotkeyMap; // uid → registered hotkey ID
	QMap<QString, QString> hotkeyPaths;     // uid → file path (stable address for callback)
};
